### ISSUE TITLE
CRASH: Game crashes before I get a chance to click any button.

### ISSUE THREAD

**Issue by NeoNyaa** [MrFast-js/Skyblock-Tweaks#4] opened 2024-10-30 08:40 UTC
## Describe the bug
Basically the title. 

## Additional Information
 - OS: Windows
 - Launcher: PrismLauncher
 - Other Mods: NONE
 - Crash Log: https://mclo.gs/we0hNnk#L205

**Comment by NeoNyaa** [comment] 2024-10-30 08:40
It looks like the true issue lies at line 205 in the log

**Comment by j10a1n15** [comment] 2024-10-30 10:54
Caused by you having a ! in your path

https://github.com/MrFast-js/Skyblock-Tweaks/blob/0e9288a3046827cbef1e197d212b8f3482b78ed5/src/main/java/mrfast/sbt/mixins/init/MixinPlugin.java#L56

**Comment by MrFast-js** [comment] 2024-10-30 11:34
As j10 said it's a file name problem, could you rename whatever folder has a exclamation mark (likely .Minecraft, or windows user)

**Comment by R-aMcC** [comment] 2024-10-30 17:58
Wait if the start thing returns something like this:
`file:/C:/Users/Wyan/AppData/Roaming/.minecraft/mods/SecretRoutes-0.4.11.jar!/xyz/yourboykyle/secretroutes/Main.class`
And you always know what the class name is, cant you just like remove starting at the `!/xyz/yourboykyle/` ? 

So idk what class it is exactly but in my case i would go

`return new URL(string.substring(4).split("!/xyz/yourboykyle/")[0]` 
returns -> C:/Users/Wyan/AppData/Roaming/.minecraft/mods/SecretRoutes-0.4.11.jar

**Comment by MrFast-js** [comment] 2024-10-30 18:00
Will be fixed in next update

**Comment by MrFast-js** [comment] 2024-10-30 22:25
https://github.com/MrFast-js/Skyblock-Tweaks/commit/2f67d7c75924b15e6125805284254bc23843dbb5
Fixed in this commit, thank you for the bug report!

**Closed by MrFast-js** 2024-10-30 22:25 UTC

**Comment by NeoNyaa** [comment] 2024-10-30 22:51
Just tested the latest action artifact and so far no crashes
